### ISSUE TITLE
すでに開いている作業中のターミナルで実行しないようにしてほしい

### ISSUE THREAD

**Issue by MurakamiShinyu** [libroworks/vivliostyle-cli-helper#4]
すでに開いている作業中のターミナルで vivliostyle-cli-helper のコマンドを実行した場合、次の問題があります。

- ユーザーがターミナル上で作業中のとき、そこでvivliostyleコマンドが実行されると、作業を続けることができない
- ターミナル上で何かコマンドを実行中の場合、vivliostyleコマンドを実行できない
- ターミナル上でカレントディレクトリを "Preview from Current File" でプレビューしようとするファイルがあるディレクトリ以外の場所に変えている場合、vivliostyle previewでのファイル変更の監視がカレントディレクトリ内でしかされないので、ファイル変更でのプレビュー更新がされない

この問題を解決するために、すでに開いているターミナルを再利用しないようにするとよいと思います。
しかし、vivliostyle-cli-helperのコマンドを実行するたびに新しいターミナルが作られるのも問題かもしれないので、Terminalのnameプロパティを "vivliostyle-cli-helper" に設定してそれをチェックするとよいのでないかと思います。
次のところ：

https://github.com/libroworks/vivliostyle-cli-helper/blob/839071733f652f03b628156fd3fdba16ba3784cb/extension.js#L52

次のように修正するとどうでしょう：

```js
		const term = vscode.window.activeTerminal?.name === "vivliostyle-cli-helper" ? vscode.window.activeTerminal : vscode.window.createTerminal("vivliostyle-cli-helper");
```

**Comment by lwohtsu** [comment]
この変更を反映するとともに、55行目のシェルの種類を取得するコードを変更しました（ターミナル名が変わるとterm.creationOptions.shellPathがなぜかundefinedになるため）。
```
if(vscode.env.shell.includes('powershell') && shellcommand.indexOf('vivliostyle') === 0){
```
